### PR TITLE
 Add spectrum shift preprocessor

### PR DESCRIPTION
**Pull request by markotoplak**
Cleaned up #132 

@borondics , can you check if it still works as it should?

### CODE REVIEW

**Comment by stuart-cls** [comment]
This seems to work, but I wonder why it is not part of baseline correction as "Offset" or similar? Especially considering all the interest in reducing preprocessors in the GUI in #128 . Maybe I'm missing something?

**Comment by markotoplak** [comment]
@stuart-cls That is a good point. I am merging this one for now, but yes, we can and should reorganize if we see fit.

**Comment by borondics** [comment]
I think spectral shift can be an operation by itself without baseline
correction, although I made this to be able to shift the baseline corrected
spectra to 1 (100%) for transmission data.

**Comment by stuart-cls** [comment]
It's semantics really, but to me shifting the baseline of the spectrum is a kind of baseline correction. Anyway, not a big deal.

**Pull request merged**
